name: dynamic_table_example
description: This is the example app for dynamic_table package for flutter.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_table:
    path: ./datatable
  url_launcher: ^6.1.11
  stacked_services: ^1.5.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
